[[language]]
name = "bash"
auto-format = true

# add in file
[language-server.ansible-language-server]
command = "ansible-language-server"
args = ["--stdio"]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language.config]
checkOnSave = {command = "clippy"}
cargo = { "features" = "all" }

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "c"
auto-format = true
scope = "source.c"
file-types = ["c", "h"]
roots = ["compile_commands.json"]
language-server = { command = "clangd" }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
