[[language]]
name = "bash"
scope = "source.shell"
file-types = ["sh"]
comment-token = "#"
indent = { tab-width = 4, unit = "  " }
formatter = { command = "shfmt" , args = ["-s", "-ci"] }
language-servers = [ "bash-language-server" ]
auto-format = true


[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
comment-token = "//"
indent = { tab-width = 4, unit = "   " }
#formatter = { command = "rustfmt" , args = ["--emit=stdout"] }
language-servers = [ "rust-analyzer" ]
auto-format = true

[[language]]
name = "go"
scope = "source.go"
file-types = ["go"]
comment-token = "//"
indent = { tab-width = 4, unit = "   " }
formatter = { command = "gofmt" , args = ["-s"] }
language-servers = [ "gopls" ]
auto-format = true

[[language]]
name = "php"
scope = "source.php"
file-types = ["php"]
comment-token = "//"
indent = { tab-width = 4, unit = "   " }
formatter = { command = "php-cs-fixer" , args = ["fix", "--using-cache=no"] }
language-servers = [ "intelephense" ]
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts"]
comment-token = "//"
indent = { tab-width = 4, unit = "   " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [ "typescript-language-server" ]
auto-format = true


[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "babel"] }
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "   " }
auto-format = true

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml", "yml"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
formatter = { command = "prettier" , args = ["--stdin-filepath", "${INPUT}"] }
language-servers = [ "yaml-language-server" ]
auto-format = true

[[language]]
name = "c"
auto-format = true
scope = "source.c"
file-types = ["c", "h"]
roots = ["compile_commands.json"]
language-servers = [ "clangd" ]

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
comment-token = "#"
indent = { tab-width = 4, unit = " " }
formatter = { command = "black" , args = ["--fast", "--quiet"] }
language-servers = [ "pyright" ]
auto-format = true

[[language]]
name = "haskell"
scope = "source.haskell"
file-types = ["hs"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "ormolu" , args = [] }
language-servers = [ "haskell-language-server-wrapper" ]
auto-format = true

